On some Windows environments, symlink fails with:
OSError: [WinError 1314] A required privilege is not held by the client

In such cases, resort to copying the files.